name: recipe-env
channels:
  - conda-forge
dependencies:
  - python=3.8.13
  - ipdb=0.13.9
  - flask
  - flask-sqlalchemy=3.0.3
  - werkzeug=2.2.2
  - flask-migrate
  - sqlalchemy-serializer
  - flask-restful
  - flask-cors
  - faker
  - bcrypt
  - flask-bcrypt
  - flask-jwt-extended
  - cloudinary
  - pip
