name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Add server directory to PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)/server" >> $GITHUB_ENV

    - name: Run unit tests
      run: |
        pytest server/test_app.py
      env:
        PYTHONPATH: ${{ env.PYTHONPATH }}
