name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: '3.10'
        activate-environment: base
        auto-update-conda: true

    - name: Initialize Conda
      shell: bash
      run: |
        source ~/.bashrc
        conda init bash
        conda activate base

    - name: Install dependencies
      shell: bash
      run: |
        conda env update --file environment.yml --name base || conda env create --file environment.yml --name base
        conda activate base

    - name: Lint with flake8
      shell: bash
      run: |
        conda install -y flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      shell: bash
      run: |
        conda install -y pytest
        pytest
