name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: '3.10'
        auto-update-conda: true

    - name: Initialize Conda
      run: |
        conda config --set always_yes yes --set changeps1 no
        conda init bash
        conda update -q conda
        conda info -a
      shell: bash

    - name: Create and activate environment
      run: |
        conda env create --file server/environment.yml --name recipe-env || conda env update --file server/environment.yml --name recipe-env
        echo "conda activate recipe-env" >> $GITHUB_ENV
      shell: bash

    - name: Lint with flake8
      run: |
        source $(conda info --base)/etc/profile.d/conda.sh
        conda activate recipe-env
        conda install -c conda-forge flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      shell: bash

    - name: Test with pytest
      run: |
        source $(conda info --base)/etc/profile.d/conda.sh
        conda activate recipe-env
        conda install -c conda-forge pytest
        pytest
      shell: bash
